### ISSUE TITLE
OpenSSL error "urlopen error EOF occurred in violation of protocol (_ssl.c:581)"

### ISSUE THREAD

**Issue by jesperronn** [svalgaard/fskintra#15]
Not sure if this is only related to OSX or to the libraries Python uses. I am unable even to log in after updating machine with security fixes, etc

OSX yosemite, Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

````
$ ~/src/fskintra/fskintra.py -v
Henter liste af børn
skoleGetURL: Trying to fetch https://www.XXX.skoleintra.dk/Infoweb/Fi2/Faneblade.asp
Login
Login på skoleintra
skoleLogin: URL https://www.XXX.skoleintra.dk/Infoweb/Fi2/Login.asp
Traceback (most recent call last):
  File "/Users/jesper/src/fskintra/fskintra.py", line 13, in <module>
    cnames = skoleintra.schildren.skoleGetChildren()
  File "/Users/jesper/src/fskintra/skoleintra/schildren.py", line 25, in skoleGetChildren
    data = surllib.skoleGetURL(URL, asSoup=True, noCache=True)
  File "/Users/jesper/src/fskintra/skoleintra/surllib.py", line 164, in skoleGetURL
    skoleLogin()
  File "/Users/jesper/src/fskintra/skoleintra/surllib.py", line 82, in skoleLogin
    br.open(URL_LOGIN)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 230, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 344, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 332, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1170, in https_open
    return self.do_open(conn_factory, req)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1118, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>

```


There is a possible explanation here http://anotherlayer.net/2014/10/16/forcing-tls1-in-pythons-urllib2-on-osx/ but I cannot get it to work directly for now. Anybody else facing this problem?

**Comment by svalgaard** [comment]
Hi Jesper

Just to be sure that this is not a firewall issue, could you maybe try to run this: 
```
python -c 'import urllib; print urllib.urlopen("https://example.com/").read(); print "ok"'
```
It should get+print the contents of https://example.com/.

I guess that it's more likely to be the other problem mentioned in your link.

**Comment by jesperronn** [comment]
@svalgaard 
still the same error for both https://example.com and also this Forældreintra instance:

```
 python -c 'import urllib; print urllib.urlopen("https://www.bagsvaerdskole.skoleintra.dk/Infoweb/Fi2/Default.asp").read(); print "ok"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:581)
```

**Comment by svalgaard** [comment]
Hej Jesper.
Prøv lige at se, om problemet ikke er løst med nyeste version af dev branchen?
God påske,
Jens

**Comment by jesperronn** [comment]
Hej Jens det virker, HURRAA! Flot klaret, Jens, og god påske!

**Comment by svalgaard** [comment]
Det ser ud til at have kørt fint de sidste par dage... Så det bliver lagt i 'master'...
