### ISSUE TITLE
Encoding problem i beskedoversigten

### ISSUE THREAD

**Issue by jesperronn** [svalgaard/fskintra#21]
Jeg får pludselig følgende fejl når scriptet når til beskedoversigten:

```
Bakke-URL: https://www.bagkost.skoleintra.dk/Infoweb/Fi/Besked/Oversigt.asp?Bakke=ind
Traceback (most recent call last):
  File "/Users/jesper/src/fskintra/fskintra.py", line 20, in <module>
    skoleintra.pgDialogue.skoleDialogue()
  File "/Users/jesper/src/fskintra/skoleintra/pgDialogue.py", line 100, in skoleDialogue
    diaFindMessages(data)
  File "/Users/jesper/src/fskintra/skoleintra/pgDialogue.py", line 76, in diaFindMessages
    if diaExamineMessage(lurl, mid):
  File "/Users/jesper/src/fskintra/skoleintra/pgDialogue.py", line 17, in diaExamineMessage
    bs = surllib.skoleGetURL(url, True)
  File "/Users/jesper/src/fskintra/skoleintra/surllib.py", line 207, in skoleGetURL
    data = beautify(data)
  File "/Users/jesper/src/fskintra/skoleintra/surllib.py", line 23, in beautify
    convertEntities=BeautifulSoup.BeautifulStoneSoup.HTML_ENTITIES)
  File "/usr/local/lib/python2.7/site-packages/BeautifulSoup.py", line 1522, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/BeautifulSoup.py", line 1147, in __init__
    self._feed(isHTML=isHTML)
  File "/usr/local/lib/python2.7/site-packages/BeautifulSoup.py", line 1189, in _feed
    SGMLParser.feed(self, markup)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sgmllib.py", line 104, in feed
    self.goahead(0)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sgmllib.py", line 186, in goahead
    self.handle_charref(name)
  File "/usr/local/lib/python2.7/site-packages/BeautifulSoup.py", line 1398, in handle_charref
    data = unichr(int(ref))
ValueError: unichr() arg not in range(0x10000) (narrow Python build)

``` 

JEg får samme fejl uanset om jeg kører master branchen (15451b5) eller dev (188ff22).
Måske relateret til #20?

**Comment by svalgaard** [comment]
Givet nedenstående to linjer ligner det at der er et helt andet problem. 
```
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sgmllib.py", line 186, in goahead
    self.handle_charref(name)
  File "/usr/local/lib/python2.7/site-packages/BeautifulSoup.py", line 1398, in handle_charref
    data = unichr(int(ref))
```

Kan jeg måske få dig til at sende mig indholdet af den html fil, det går galt på? Så vil det nok være lettere at præcist hvad der er galt + finde en løsning.

**Comment by jesperronn** [comment]
@svalgaard jeg har luret fejlen. En emoji smiley encoded kan åbenbart ødelægge BeautifulSoup parsingen. Problemet var denne smiley `&#128540;` &#128540; 

![screen_shot_2015-04-22_at_22_54_10](https://cloud.githubusercontent.com/assets/6267/7285152/d81030c0-e942-11e4-9d17-c5f01327f5ad.png)

**Comment by jesperronn** [comment]
Her var et andet eksempel fra en mail som fejler:

> Super fint initiativ &#128516;

Med emoji `&#128516;` som er  &#128516;

Igen samme fejl i en anden mail

**Comment by svalgaard** [comment]
Hej Jesper.
Problemet med "brede" unicode tegn som &#128540;  burde være væk med nyeste version af dev branchen.

**Comment by jesperronn** [comment]
Jeg har opdateret master og tror det virker... skal nok sige til hvis der kommer flere sindssyge emojis som driller 😄😜
