### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by thluDK** [svalgaard/fskintra#28]
Jeg får nedenstående fejl hver gang jeg kører fksintra.py 

Jeg får tilsynladende nye beskeder, men nok kun fra de punker som behandles før fejlen opstår.

```text
thomas@thing2:~/thomas/fskintra$ ./fskintra.py --config-file=/home/thomas/thomas/skoleintra.txt
Henter liste af børn
Login på skoleintra
skoleLogin: Prøver igen med sslfix
Vælger [Magnus 0A]
Kigger efter nye adresser
Behandler forsiden
Kategori [Motionsdag 2015] (hoppes over)
Kategori [Klassens opslagstavle]
Kategori [Skema for Magnus 0A for skoleåret 2015/16]
Kategori [Dialog mellem skole og hjem] (hoppes over)
Kategori [Nyeste meddelelser fra kontoret] (hoppes over)
Kategori [Nyeste dokumenter] (hoppes over)
Kategori [Information om klassen] (hoppes over)
Kategori [Nyt fra ...]
Kategori [Klassens fotoalbum]
Kategori [Ugeplan for uge 45-2015]
Behandler beskeder i bakken ind
Bakke-URL: https://www.ulkebol.skoleintra.dk/Infoweb/Fi/Besked/Oversigt.asp?Bakke=ind
Behandler beskeder i bakken ud
Bakke-URL: https://www.ulkebol.skoleintra.dk/Infoweb/Fi/Besked/Oversigt.asp?Bakke=ud
Kigger efter nye dokumenter
Traceback (most recent call last):
  File "./fskintra.py", line 21, in <module>
    skoleintra.pgDocuments.skoleDocuments()
  File "/mnt/homes/thomas/fskintra/skoleintra/pgDocuments.py", line 97, in skoleDocuments
    docFindDocuments(bs)
  File "/mnt/homes/thomas/fskintra/skoleintra/pgDocuments.py", line 48, in docFindDocuments
    assert('Dokliste' in url)
AssertionError
thomas@thing2:~/thomas/fskintra$ 
thomas@thing2:~/thomas/fskintra$ git pull
Already up-to-date.
thomas@thing2:~/thomas/fskintra$ python -V
Python 2.7.10+
thomas@thing2:~/thomas/fskintra$
```

**Comment by sorenweber** [comment]
Jeg får det samme. Her er den sidste del af fskintra.py -v
```
Kigger efter nye dokumenter
skoleGetURL: Trying to fetch http://www.sktjosefsskole.skoleintra.dk/Infoweb/Fi/Dokumentarkiv/Dokliste.asp child=Bjørn 2A
Traceback (most recent call last):
  File "./fskintra.py", line 21, in <module>
    skoleintra.pgDocuments.skoleDocuments()
  File "/home/soren/fskintra/skoleintra/pgDocuments.py", line 97, in skoleDocuments
    docFindDocuments(bs)
  File "/home/soren/fskintra/skoleintra/pgDocuments.py", line 48, in docFindDocuments
    assert('Dokliste' in url)
AssertionError
```

**Comment by svalgaard** [comment]
Dette burde være rettet med commit ca281b006f8b47652a74ca99f142d14c46d9bd93 i dev-branchen, som nu er røget ind i master. Kan en af jer lige prøve om det hjælper?

**Comment by thluDK** [comment]
Ja det virker nu for mig

Mange tak for hurtig respons og et godt program !

**Comment by svalgaard** [comment]
Det var godt at høre - og dejligt at andre kan bruge fskintra... :)
