### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by sorenweber** [svalgaard/fskintra#29]
Det var super så hurtigt du fiksede #28, tak for det, men nu støder jeg på en ny fejl.

 ```
./fskintra.py -v
<en masse som ikke er relevant>
Vælger [Kontaktforældre]
skoleGetURL: Trying to fetch http://www.sktjosefsskole.skoleintra.dk/Infoweb/Fi2/OpdaterLogfil.asp?Id=Kon child=Emma 0A
Kigger efter nye adresser
skoleGetURL: Henter fra cache http://www.sktjosefsskole.skoleintra.dk/Infoweb/Fi/Klasselister.asp
skoleGetURL: /home/soren/.skoleintra/cache/http/www.sktjosefsskole.skoleintra.dk/Infoweb/Fi/Klasselister.asp&CHILDNAME=Kontaktforældre
Traceback (most recent call last):
  File "./fskintra.py", line 18, in <module>
    skoleintra.pgContactLists.skoleContactLists()
  File "/home/soren/fskintra/skoleintra/pgContactLists.py", line 72, in skoleContactLists
    fst = sel.option['value']
TypeError: 'NoneType' object has no attribute '__getitem__'

python -V
Python 2.7.6
```

**Comment by svalgaard** [comment]
Det ligner at fskintra tror at "Kontaktforældre" er navnet på et barn, hvilket sjældent er tilfældet...

**Comment by sorenweber** [comment]
Perfekt, hurtig igen! Nu kører den igennem helt uden fejl. Mange tak for det.
