### ISSUE TITLE
AssertionError:     assert(len(maint) == 1)  # assume exactly one main table

### ISSUE THREAD

**Issue by jenshenneberg** [svalgaard/fskintra#30]
Jeg får nedenstående fejl når jeg kører fskintra. Jeg ved ikke om det har betydning, men jeg kører på en RaspberryPi. Det er første gang jeg forsøger med fskintra.

```
pi@raspi2:~/fskintra $ python fskintra.py -v
Henter liste af børn
skoleGetURL: Trying to fetch http://www.korsager.kk.dk/Infoweb/Fi2/Faneblade.asp child=
Login
Login på skoleintra
skoleLogin: URL https://www.korsager.kk.dk/Infoweb/Fi2/Login.asp
skoleLogin: Brugernavn jenhen
Vælger [Thor 0X]
skoleGetURL: Trying to fetch http://www.korsager.kk.dk/Infoweb/Fi2/OpdaterLogfil.asp?Id=2817&Checksum=5adf4376a08b8a8375dd2b95bcfd6b0b child=
Kigger efter nye adresser
skoleGetURL: Henter fra cache http://www.korsager.kk.dk/Infoweb/Fi/Klasselister.asp
skoleGetURL: /home/pi/.skoleintra/cache/http/www.korsager.kk.dk/Infoweb/Fi/Klasselister.asp&CHILDNAME=Thor 0X
skoleGetURL: Henter fra cache http://www.korsager.kk.dk/Infoweb/Fi/Klasselister.asp
skoleGetURL: /home/pi/.skoleintra/cache/http/www.korsager.kk.dk/Infoweb/Fi/Klasselister.asp&CHILDNAME=Thor 0XfKlasse=00X&fSortering=V1&fSkjult=ON&B1=Vis+liste&R1=V5
Hopper tidligere sendt besked over: <semail.Message type='contactList' date='30-05-2016' title=u'Kontaktoplysninger i 0X'>
skoleGetURL: Henter fra cache http://www.korsager.kk.dk/Infoweb/Fi/Klasselister.asp
skoleGetURL: /home/pi/.skoleintra/cache/http/www.korsager.kk.dk/Infoweb/Fi/Klasselister.asp&CHILDNAME=Thor 0XfKlasse=00X&fSortering=V1&fSkjult=ON&B1=Vis+liste&R1=V6
Hopper tidligere sendt besked over: <semail.Message type='contactList' date='30-05-2016' title=u'For\xe6ldrenes e-mailadresser i 0X'>
Behandler forsiden
skoleGetURL: Trying to fetch http://www.korsager.kk.dk/Infoweb/Fi2/Forside.asp child=Thor 0X
Traceback (most recent call last):
  File "fskintra.py", line 19, in <module>
    skoleintra.pgFrontpage.skoleFrontpage()
  File "/home/pi/fskintra/skoleintra/pgFrontpage.py", line 199, in skoleFrontpage
    assert(len(maint) == 1)  # assume exactly one main table
AssertionError
pi@raspi2:~/fskintra $ python -V
Python 2.7.9
pi@raspi2:~/fskintra $ git pull
Already up-to-date.
pi@raspi2:~/fskintra $

```

**Comment by svalgaard** [comment]
Hej Jens

Blot for at være sikker på, at det ikke skyldes en fil, der tidligere er hentet forkert, prøv først at køre flg.
`python fskintra.py --skip-cache -v`

Hvis det ikke virker, må jeres skole have et forsideelement, som vores ikke har. Du kan enten fjerne nogen af dem, eller du gerne sende mig indholdet af forsiden og jeg vil prøve at se, hvad det er der går galt:

1. Log på skolens hjemmeside og vælg Thor
2. Gå direkte ind på siden http://www.korsager.kk.dk/Infoweb/Fi2/Forside.asp - du vil så få selve forsiden uden menu til venstre.
3. Gem som html (kun HTML ikke komplet)
4. Send til mig (github AT svalgaard.net)

**Comment by jenshenneberg** [comment]
Hej Jens,

Mange tak for svaret og hjælpen med dette.
Jeg forsøgte at køre uden cache (med kommandoen ovenfor), og det hjalp desværre ikke. Jeg sender mail med html filen.

**Comment by svalgaard** [comment]
Meget forsinket burde problemet nu være løst i 25941cf. Jens: genåbn sagen, hvis det ikke er tilfældet.
