### ISSUE TITLE
fskintra fails with WRONG_SIGNATURE_TYPE

### ISSUE THREAD

**Issue by nifhub** [svalgaard/fskintra#45]
I had fskintra working since august 2019. Then it stopped working around first half of february 2020. 

Today I looked closer at the error:

```
-> docker run --rm -it -v  ~/.skoleintra:/root/.skoleintra fskintra -v -v
Henter liste af børn
Henter tidligere browsertilstand fra /root/.skoleintra/CACHENAVN-cache/SKOLE.m.skoleintra.dk-BRUGER.state
Login
Log ind på ForældreIntra
Genbruger sidst kendte forside URL https://SKOLE.m.skoleintra.dk/parent/NUMMER/BARN/Index
Traceback (most recent call last):
  File "fskintra.py", line 35, in <module>
    main()
  File "fskintra.py", line 24, in main
    cnames = skoleintra.schildren.getChildren()
  File "/fskintra/skoleintra/schildren.py", line 24, in getChildren
    data = surllib.skoleLogin()
  File "/fskintra/skoleintra/surllib.py", line 179, in skoleLogin
    resp = br.open(url)
  File "/fskintra/skoleintra/surllib.py", line 123, in open
    resp = mechanize.Browser.open(self, url, *args, **aargs)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 254, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 284, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_opener.py", line 206, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 467, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_opener.py", line 224, in error
    result = apply(self._call_chain, args)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 340, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 586, in http_error_302
    return self.parent.open(new)
  File "/fskintra/skoleintra/surllib.py", line 123, in open
    resp = mechanize.Browser.open(self, url, *args, **aargs)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 254, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 284, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_opener.py", line 206, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 467, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_opener.py", line 224, in error
    result = apply(self._call_chain, args)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 340, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 586, in http_error_302
    return self.parent.open(new)
  File "/fskintra/skoleintra/surllib.py", line 123, in open
    resp = mechanize.Browser.open(self, url, *args, **aargs)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 254, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 284, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_opener.py", line 195, in open
    response = urlopen(self, req, data)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 352, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 340, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1215, in https_open
    return self.do_open(conn_factory, req)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1160, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:727)>
```
I have run fskintra without docker all the time but now tried docker to exclude that I have messed something up somewhere. I get exactly same error running with or without docker.

I tried to go two commits back (to 01642ae4715b3c69cda68c48c5a8fcbece994082) but same error. So it does not seem to relate to any code changes in fskintra

I tried to run:

```
python -c 'import urllib; print urllib.urlopen("https://example.com/").read(); print "ok"'
```
And it returns the contens just fine.

I tried to rename .skoleintra and start over with at new config. Still same error.

**Comment by svalgaard** [comment]
As far as I can see this issue is probably not related fskintra but due to a security hardening in Python / your distribution / including docker. You could check to see whether it can be fixed as shown in [this issue from the youtube-dl project](https://github.com/ytdl-org/youtube-dl/issues/22665#issuecomment-570762228).

If not, please send me the URL of the school homepage either here or to github AT svalgaard.net, and I'll have a look. I cannot reproduce the error at my children's school as they have switched to AULA.

**Comment by nifhub** [comment]
You are right. Thanks for the hint. 

I did upgrade to Debian buster around the time it stopped working.  As suggested in the linked issue setting
```
CipherString = DEFAULT@SECLEVEL=1
```
Does make the error go away. So it is some security hardening regarding openssl. I'll just have to figure out how I want to run fskintra now, without degrading openssl security in buster. (probably in a container with stretch).
