### ISSUE TITLE
Fejler ved samtaler/arrangementer

### ISSUE THREAD

**Issue by twister5800** [svalgaard/fskintra#46]
Hejsa,
Tak for et godt værktøj :-)

Jeg har dog denne fejl:

[xxxBarn 1A] Kigger efter nye samtaler/arrangementer
skoleGetURL: Prøver at hente https://xxxxskole.m.skoleintra.dk/parent/3000/xxxbarn/signup/conversation
Traceback (most recent call last):
  File "./fskintra.py", line 35, in <module>
    main()
  File "./fskintra.py", line 28, in main
    sf.maybeRun(cnames)
  File "/home/dagbog/public_html/fskintra/skoleintra/config.py", line 434, in maybeRun
    self.run(cnames)
  File "/home/dagbog/public_html/fskintra/skoleintra/config.py", line 444, in run
    self.f(cname)
  File "/home/dagbog/public_html/fskintra/skoleintra/pgSignup.py", line 57, in skoleSignup
    bs = surllib.skoleGetURL(url, True, MAX_CACHE_AGE)
  File "/home/dagbog/public_html/fskintra/skoleintra/surllib.py", line 391, in skoleGetURL
    resp = br.open(qurl, postData)
  File "/home/dagbog/public_html/fskintra/skoleintra/surllib.py", line 123, in open
    resp = mechanize.Browser.open(self, url, *args, **aargs)
  File "/usr/lib/python2.7/site-packages/mechanize/_mechanize.py", line 254, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/mechanize/_mechanize.py", line 310, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found

Men jeg tror URL er ændret, det hvis jeg går ind under "blanketter" som det hedder nu, er URL:
https://xxxskole.m.skoleintra.dk/parent/3000/xxxBarn/forms/open

Mvh. Martin :-)

**Comment by svalgaard** [comment]
Hej Martin
Dejligt at du kan bruge programmet. Mine børns skoler er skiftet til AULA så jeg har desværre ikke mulighed for at hjælpe med at rette programmet til længere.
Hvis du har mulighed for selv at gøre det (?), må du meget gerne sende opdatererede filer herind eller direkte til mig.
Alternativt tænker jeg at jeg vil slå "samtaler/arrangementer"-modulet fra...
- Jens

**Comment by svalgaard** [comment]
Jeg har slået tilmeldings-modulet fra i første omgang - så må vi se om der er nogen der kan tage teten på et tidspunkt. :)

**Comment by twister5800** [comment]
Hej Jens,

helt OK tak fordi du gad ændre i det :-)

Martin
